#Default AnimalGuard Config Version 1.0
notify-outdated: true
auto-download-updates: false
allow-pvp-tameable: true
allow-sheep-shearing: false
allow-sheep-dye: false
allow-mooshroom-shearing: false
allow-mob-leashing: false
allow-cow-milking: true
protect-from-player:
     - Chicken
     - Cow
     - MushroomCow
     - Ozelot
     - Pig
     - Sheep
     - Wolf
     - VillagerGolem
     - SnowMan
     - EntityHorse
protect-from-monsters:
     - Villager
debug: false