#Default AnimalGuard Config Version 1.0
notify-outdated: true
auto-download-updates: false
debug: false
allow-sheep-shearing: false
protect-from-player:
     - Chicken
     - Cow
     - MushroomCow
     - Ozelot
     - Pig
     - Sheep
     - Wolf
     - VillagerGolem
     - SnowMan
     - EntityHorse
protect-from-monsters:
     - Villager